// TicketKati - Bangladesh Bus & Place Data

export const BUSES = [
  {
    id: 'bus-01',
    name: 'Drutogami Express',
    nameBn: 'দ্রুতগামী এক্সপ্রেস',
    type: 'AC',
    logo: '🚌',
    color: '#E8242A',
    rating: 4.5,
    totalSeats: 40,
    perSeatPrice: 350,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Recliner Seat'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'bogura', 'rangpur'],
    schedule: ['06:00', '08:00', '10:00', '14:00', '18:00', '22:00'],
    description: 'Premium AC service with modern amenities',
  },
  {
    id: 'bus-02',
    name: 'Rajib Paribahan',
    nameBn: 'রাজিব পরিবহন',
    type: 'Non-AC',
    logo: '🚌',
    color: '#1A8A4A',
    rating: 4.2,
    totalSeats: 44,
    perSeatPrice: 200,
    amenities: ['Fan', 'Comfortable Seat', 'Luggage Space'],
    routes: ['dhaka', 'narayanganj', 'cumilla', 'chittagong'],
    schedule: ['07:00', '09:30', '12:00', '15:00', '20:00'],
    description: 'Reliable and affordable inter-city service',
  },
  {
    id: 'bus-03',
    name: 'Hanif Enterprise',
    nameBn: 'হানিফ এন্টারপ্রাইজ',
    type: 'AC',
    logo: '🚌',
    color: '#F5A623',
    rating: 4.7,
    totalSeats: 40,
    perSeatPrice: 500,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Blanket', 'Snacks'],
    routes: ['dhaka', 'sylhet', 'moulvibazar'],
    schedule: ['07:30', '10:00', '13:00', '17:00', '22:30'],
    description: 'Bangladesh\'s most trusted long-route bus service',
  },
  {
    id: 'bus-04',
    name: 'Dhaka-Tangail Bhuyapuri',
    nameBn: 'ঢাকা-টাঙ্গাইল ভূয়াপুরী',
    type: 'Non-AC',
    logo: '🚌',
    color: '#3B82F6',
    rating: 3.9,
    totalSeats: 44,
    perSeatPrice: 150,
    amenities: ['Fan', 'Economy Seat'],
    routes: ['dhaka', 'gazipur', 'tangail', 'mymensingh'],
    schedule: ['06:30', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00'],
    description: 'Frequent daily service on Dhaka-Tangail route',
  },
  {
    id: 'bus-05',
    name: 'Sirajganj Travel',
    nameBn: 'সিরাজগঞ্জ ট্রাভেল',
    type: 'AC',
    logo: '🚌',
    color: '#8B5CF6',
    rating: 4.3,
    totalSeats: 40,
    perSeatPrice: 320,
    amenities: ['AC', 'Recliner Seat', 'USB Charging', 'Water Bottle'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'pabna'],
    schedule: ['06:00', '09:00', '12:00', '15:00', '19:00', '22:00'],
    description: 'Comfortable North Bengal connectivity',
  },
  {
    id: 'bus-06',
    name: 'Lalmonirhat Express',
    nameBn: 'লালমনিরহাট এক্সপ্রেস',
    type: 'AC',
    logo: '🚌',
    color: '#EC4899',
    rating: 4.1,
    totalSeats: 40,
    perSeatPrice: 600,
    amenities: ['AC', 'Blanket', 'Pillow', 'USB Charging', 'Recliner'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'bogura', 'rangpur', 'lalmonirhat'],
    schedule: ['08:00', '14:00', '21:00'],
    description: 'Overnight comfort service to far north',
  },
  {
    id: 'bus-07',
    name: 'Comilla Travel',
    nameBn: 'কুমিল্লা ট্রাভেল',
    type: 'Non-AC',
    logo: '🚌',
    color: '#14B8A6',
    rating: 4.0,
    totalSeats: 44,
    perSeatPrice: 180,
    amenities: ['Fan', 'Comfortable Seat', 'Luggage'],
    routes: ['dhaka', 'narayanganj', 'cumilla', 'feni'],
    schedule: ['06:00', '07:30', '09:00', '11:00', '13:00', '15:00', '17:00', '19:00'],
    description: 'Quick and frequent Dhaka-Comilla runs',
  },
  {
    id: 'bus-08',
    name: "Cox's Bazar Sleeper Coach",
    nameBn: 'কক্সবাজার স্লিপার কোচ',
    type: 'Sleeper',
    logo: '🚌',
    color: '#F97316',
    rating: 4.8,
    totalSeats: 28,
    perSeatPrice: 900,
    amenities: ['AC', 'Sleeper Berth', 'Curtain', 'USB Charging', 'Blanket', 'Pillow', 'Snacks'],
    routes: ['dhaka', 'chittagong', 'coxsbazar'],
    schedule: ['21:00', '22:00', '23:00'],
    description: 'Luxury sleeper berths for overnight travel',
  },
];

export const PLACES = [
  {
    id: 'dhaka',
    name: 'Dhaka',
    nameBn: 'ঢাকা',
    terminal: 'Multiple Terminals',
    subLocations: [
      { id: 'dhaka-sayedabad', name: 'Sayedabad Bus Terminal', nameBn: 'সায়েদাবাদ বাস টার্মিনাল' },
      { id: 'dhaka-gabtoli', name: 'Gabtoli Bus Terminal', nameBn: 'গাবতলী বাস টার্মিনাল' },
      { id: 'dhaka-mohakhali', name: 'Mohakhali Bus Terminal', nameBn: 'মহাখালী বাস টার্মিনাল' },
      { id: 'dhaka-mirpur', name: 'Mirpur Bus Stand', nameBn: 'মিরপুর বাস স্ট্যান্ড' },
      { id: 'dhaka-uttara', name: 'Uttara Bus Stand', nameBn: 'উত্তরা বাস স্ট্যান্ড' },
      { id: 'dhaka-gulistan', name: 'Gulistan Bus Stand', nameBn: 'গুলিস্তান বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'chittagong',
    name: 'Chittagong',
    nameBn: 'চট্টগ্রাম',
    terminal: 'Dampara Terminal',
    subLocations: [
      { id: 'ctg-dampara', name: 'Dampara Bus Terminal', nameBn: 'দামপাড়া বাস টার্মিনাল' },
      { id: 'ctg-oxygen', name: 'Oxygen Bus Stand', nameBn: 'অক্সিজেন বাস স্ট্যান্ড' },
      { id: 'ctg-bahaddarhat', name: 'Bahaddarhat Terminal', nameBn: 'বহদ্দারহাট টার্মিনাল' },
      { id: 'ctg-agrabad', name: 'Agrabad Bus Stand', nameBn: 'আগ্রাবাদ বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'sylhet',
    name: 'Sylhet',
    nameBn: 'সিলেট',
    terminal: 'Kadamtoli Terminal',
    subLocations: [
      { id: 'syl-kadamtoli', name: 'Kadamtoli Bus Terminal', nameBn: 'কদমতলী বাস টার্মিনাল' },
      { id: 'syl-kumargaon', name: 'Kumargaon Terminal', nameBn: 'কুমারগাঁও টার্মিনাল' },
    ],
  },
  {
    id: 'rajshahi',
    name: 'Rajshahi',
    nameBn: 'রাজশাহী',
    terminal: 'Rajshahi Terminal',
    subLocations: [
      { id: 'raj-central', name: 'Rajshahi Central Terminal', nameBn: 'রাজশাহী কেন্দ্রীয় টার্মিনাল' },
      { id: 'raj-shiromoni', name: 'Shiromoni Bus Stand', nameBn: 'শিরোমণি বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'khulna',
    name: 'Khulna',
    nameBn: 'খুলনা',
    terminal: 'Sonadanga Terminal',
    subLocations: [
      { id: 'khu-sonadanga', name: 'Sonadanga Bus Terminal', nameBn: 'সোনাডাঙ্গা বাস টার্মিনাল' },
      { id: 'khu-rupsha', name: 'Rupsha Bus Stand', nameBn: 'রূপসা বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'barisal',
    name: 'Barisal',
    nameBn: 'বরিশাল',
    terminal: 'Notullabad Terminal',
    subLocations: [
      { id: 'bar-notullabad', name: 'Notullabad Bus Terminal', nameBn: 'নথুল্লাবাদ বাস টার্মিনাল' },
      { id: 'bar-rupatoli', name: 'Rupatoli Bus Stand', nameBn: 'রূপাতলী বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'rangpur',
    name: 'Rangpur',
    nameBn: 'রংপুর',
    terminal: 'Rangpur Central',
    subLocations: [
      { id: 'ran-central', name: 'Rangpur Central Terminal', nameBn: 'রংপুর কেন্দ্রীয় টার্মিনাল' },
      { id: 'ran-dhap', name: 'Dhap Bus Stand', nameBn: 'ধাপ বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'mymensingh',
    name: 'Mymensingh',
    nameBn: 'ময়মনসিংহ',
    terminal: 'Mymensingh Bus Terminal',
    subLocations: [
      { id: 'mym-central', name: 'Mymensingh Central Terminal', nameBn: 'ময়মনসিংহ কেন্দ্রীয় টার্মিনাল' },
      { id: 'mym-mashkanda', name: 'Mashkanda Terminal', nameBn: 'মাশকান্দা টার্মিনাল' },
    ],
  },
  {
    id: 'coxsbazar',
    name: "Cox's Bazar",
    nameBn: 'কক্সবাজার',
    terminal: "Cox's Bazar Terminal",
    subLocations: [
      { id: 'cox-central', name: "Cox's Bazar Central Terminal", nameBn: 'কক্সবাজার কেন্দ্রীয় টার্মিনাল' },
      { id: 'cox-kolatoli', name: 'Kolatoli Bus Stand', nameBn: 'কলাতলী বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'cumilla',
    name: 'Cumilla',
    nameBn: 'কুমিল্লা',
    terminal: 'Cumilla Bus Stand',
    subLocations: [
      { id: 'cum-central', name: 'Cumilla Central Bus Stand', nameBn: 'কুমিল্লা কেন্দ্রীয় বাস স্ট্যান্ড' },
      { id: 'cum-kandirpar', name: 'Kandirpar Bus Stand', nameBn: 'কান্দিরপাড় বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'gazipur',
    name: 'Gazipur',
    nameBn: 'গাজীপুর',
    terminal: 'Chandra Terminal',
    subLocations: [
      { id: 'gaz-chandra', name: 'Chandra Bus Terminal', nameBn: 'চন্দ্রা বাস টার্মিনাল' },
      { id: 'gaz-tongi', name: 'Tongi Bus Stand', nameBn: 'টঙ্গী বাস স্ট্যান্ড' },
      { id: 'gaz-boardbazar', name: 'Board Bazar Stand', nameBn: 'বোর্ড বাজার স্ট্যান্ড' },
    ],
  },
  {
    id: 'narayanganj',
    name: 'Narayanganj',
    nameBn: 'নারায়ণগঞ্জ',
    terminal: 'Narayanganj Bus Stand',
    subLocations: [
      { id: 'nar-central', name: 'Narayanganj Central', nameBn: 'নারায়ণগঞ্জ কেন্দ্রীয়' },
      { id: 'nar-fatullah', name: 'Fatullah Bus Stand', nameBn: 'ফতুল্লা বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'tangail',
    name: 'Tangail',
    nameBn: 'টাঙ্গাইল',
    terminal: 'Tangail Central Terminal',
    subLocations: [
      { id: 'tan-central', name: 'Tangail Central Terminal', nameBn: 'টাঙ্গাইল কেন্দ্রীয় টার্মিনাল' },
      { id: 'tan-elenga', name: 'Elenga Bus Stand', nameBn: 'এলেঙ্গা বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'bogura',
    name: 'Bogura',
    nameBn: 'বগুড়া',
    terminal: 'Bogura Bus Station',
    subLocations: [
      { id: 'bog-central', name: 'Bogura Central Bus Station', nameBn: 'বগুড়া কেন্দ্রীয় বাস স্টেশন' },
      { id: 'bog-thenapara', name: 'Thenapara Bus Stand', nameBn: 'ঠেনাপাড়া বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'sirajganj',
    name: 'Sirajganj',
    nameBn: 'সিরাজগঞ্জ',
    terminal: 'Sirajganj Terminal',
    subLocations: [
      { id: 'sir-central', name: 'Sirajganj Central Terminal', nameBn: 'সিরাজগঞ্জ কেন্দ্রীয় টার্মিনাল' },
      { id: 'sir-banpara', name: 'Banpara Bus Stand', nameBn: 'বানপাড়া বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'jessore',
    name: 'Jessore',
    nameBn: 'যশোর',
    terminal: 'Jessore Bus Stand',
    subLocations: [
      { id: 'jes-central', name: 'Jessore Central Bus Stand', nameBn: 'যশোর কেন্দ্রীয় বাস স্ট্যান্ড' },
      { id: 'jes-benapole', name: 'Benapole Bus Stand', nameBn: 'বেনাপোল বাস স্ট্যান্ড' },
    ],
  },
  {
    id: 'dinajpur',
    name: 'Dinajpur',
    nameBn: 'দিনাজপুর',
    terminal: 'Dinajpur Bus Stand',
    subLocations: [
      { id: 'din-central', name: 'Dinajpur Central Bus Stand', nameBn: 'দিনাজপুর কেন্দ্রীয় বাস স্ট্যান্ড' },
      { id: 'din-munshipara', name: 'Munshipara Terminal', nameBn: 'মুন্সিপাড়া টার্মিনাল' },
    ],
  },
  { id: 'faridpur', name: 'Faridpur', nameBn: 'ফরিদপুর', terminal: 'Faridpur Bus Terminal', subLocations: [{ id: 'far-central', name: 'Faridpur Central Terminal', nameBn: 'ফরিদপুর কেন্দ্রীয় টার্মিনাল' }] },
  { id: 'gopalganj', name: 'Gopalganj', nameBn: 'গোপালগঞ্জ', terminal: 'Gopalganj Bus Stand', subLocations: [{ id: 'gop-central', name: 'Gopalganj Bus Stand', nameBn: 'গোপালগঞ্জ বাস স্ট্যান্ড' }] },
  { id: 'kishoreganj', name: 'Kishoreganj', nameBn: 'কিশোরগঞ্জ', terminal: 'Kishoreganj Terminal', subLocations: [{ id: 'kis-central', name: 'Kishoreganj Terminal', nameBn: 'কিশোরগঞ্জ টার্মিনাল' }] },
  { id: 'madaripur', name: 'Madaripur', nameBn: 'মাদারীপুর', terminal: 'Madaripur Bus Stand', subLocations: [{ id: 'mad-central', name: 'Madaripur Bus Stand', nameBn: 'মাদারীপুর বাস স্ট্যান্ড' }] },
  { id: 'manikganj', name: 'Manikganj', nameBn: 'মানিকগঞ্জ', terminal: 'Manikganj Terminal', subLocations: [{ id: 'man-central', name: 'Manikganj Terminal', nameBn: 'মানিকগঞ্জ টার্মিনাল' }] },
  { id: 'munshiganj', name: 'Munshiganj', nameBn: 'মুন্সীগঞ্জ', terminal: 'Munshiganj Bus Stand', subLocations: [{ id: 'mun-central', name: 'Munshiganj Bus Stand', nameBn: 'মুন্সীগঞ্জ বাস স্ট্যান্ড' }] },
  { id: 'narsingdi', name: 'Narsingdi', nameBn: 'নরসিংদী', terminal: 'Narsingdi Terminal', subLocations: [{ id: 'ndi-central', name: 'Narsingdi Terminal', nameBn: 'নরসিংদী টার্মিনাল' }] },
  { id: 'rajbari', name: 'Rajbari', nameBn: 'রাজবাড়ী', terminal: 'Rajbari Bus Stand', subLocations: [{ id: 'rjb-central', name: 'Rajbari Bus Stand', nameBn: 'রাজবাড়ী বাস স্ট্যান্ড' }] },
  { id: 'shariatpur', name: 'Shariatpur', nameBn: 'শরীয়তপুর', terminal: 'Shariatpur Terminal', subLocations: [{ id: 'sha-central', name: 'Shariatpur Terminal', nameBn: 'শরীয়তপুর টার্মিনাল' }] },
  { id: 'jamalpur', name: 'Jamalpur', nameBn: 'জামালপুর', terminal: 'Jamalpur Bus Stand', subLocations: [{ id: 'jam-central', name: 'Jamalpur Bus Stand', nameBn: 'জামালপুর বাস স্ট্যান্ড' }] },
  { id: 'netrokona', name: 'Netrokona', nameBn: 'নেত্রকোণা', terminal: 'Netrokona Terminal', subLocations: [{ id: 'net-central', name: 'Netrokona Terminal', nameBn: 'নেত্রকোণা টার্মিনাল' }] },
  { id: 'sherpur', name: 'Sherpur', nameBn: 'শেরপুর', terminal: 'Sherpur Bus Stand', subLocations: [{ id: 'shp-central', name: 'Sherpur Bus Stand', nameBn: 'শেরপুর বাস স্ট্যান্ড' }] },
  { id: 'bandarban', name: 'Bandarban', nameBn: 'বান্দরবান', terminal: 'Bandarban Bus Stand', subLocations: [{ id: 'ban-central', name: 'Bandarban Bus Stand', nameBn: 'বান্দরবান বাস স্ট্যান্ড' }] },
  { id: 'brahmanbaria', name: 'Brahmanbaria', nameBn: 'ব্রাহ্মণবাড়িয়া', terminal: 'Brahmanbaria Terminal', subLocations: [{ id: 'bra-central', name: 'Brahmanbaria Terminal', nameBn: 'ব্রাহ্মণবাড়িয়া টার্মিনাল' }] },
  { id: 'chandpur', name: 'Chandpur', nameBn: 'চাঁদপুর', terminal: 'Chandpur Bus Stand', subLocations: [{ id: 'cha-central', name: 'Chandpur Bus Stand', nameBn: 'চাঁদপুর বাস স্ট্যান্ড' }] },
  { id: 'feni', name: 'Feni', nameBn: 'ফেনী', terminal: 'Feni Terminal', subLocations: [{ id: 'fen-central', name: 'Feni Terminal', nameBn: 'ফেনী টার্মিনাল' }] },
  { id: 'khagrachhari', name: 'Khagrachhari', nameBn: 'খাগড়াছড়ি', terminal: 'Khagrachhari Bus Stand', subLocations: [{ id: 'kha-central', name: 'Khagrachhari Bus Stand', nameBn: 'খাগড়াছড়ি বাস স্ট্যান্ড' }] },
  { id: 'lakshmipur', name: 'Lakshmipur', nameBn: 'লক্ষ্মীপুর', terminal: 'Lakshmipur Terminal', subLocations: [{ id: 'lak-central', name: 'Lakshmipur Terminal', nameBn: 'লক্ষ্মীপুর টার্মিনাল' }] },
  { id: 'noakhali', name: 'Noakhali', nameBn: 'নোয়াখালী', terminal: 'Noakhali Bus Stand', subLocations: [{ id: 'noa-central', name: 'Noakhali Bus Stand', nameBn: 'নোয়াখালী বাস স্ট্যান্ড' }] },
  { id: 'rangamati', name: 'Rangamati', nameBn: 'রাঙামাটি', terminal: 'Rangamati Terminal', subLocations: [{ id: 'rng-central', name: 'Rangamati Terminal', nameBn: 'রাঙামাটি টার্মিনাল' }] },
  { id: 'habiganj', name: 'Habiganj', nameBn: 'হবিগঞ্জ', terminal: 'Habiganj Bus Stand', subLocations: [{ id: 'hab-central', name: 'Habiganj Bus Stand', nameBn: 'হবিগঞ্জ বাস স্ট্যান্ড' }] },
  { id: 'sunamganj', name: 'Sunamganj', nameBn: 'সুনামগঞ্জ', terminal: 'Sunamganj Terminal', subLocations: [{ id: 'sun-central', name: 'Sunamganj Terminal', nameBn: 'সুনামগঞ্জ টার্মিনাল' }] },
  { id: 'moulvibazar', name: 'Moulvibazar', nameBn: 'মৌলভীবাজার', terminal: 'Moulvibazar Terminal', subLocations: [{ id: 'mol-central', name: 'Moulvibazar Terminal', nameBn: 'মৌলভীবাজার টার্মিনাল' }] },
  { id: 'barguna', name: 'Barguna', nameBn: 'বরগুনা', terminal: 'Barguna Bus Stand', subLocations: [{ id: 'brg-central', name: 'Barguna Bus Stand', nameBn: 'বরগুনা বাস স্ট্যান্ড' }] },
  { id: 'bhola', name: 'Bhola', nameBn: 'ভোলা', terminal: 'Bhola Terminal', subLocations: [{ id: 'bho-central', name: 'Bhola Terminal', nameBn: 'ভোলা টার্মিনাল' }] },
  { id: 'jhalokati', name: 'Jhalokati', nameBn: 'ঝালকাঠি', terminal: 'Jhalokati Bus Stand', subLocations: [{ id: 'jha-central', name: 'Jhalokati Bus Stand', nameBn: 'ঝালকাঠি বাস স্ট্যান্ড' }] },
  { id: 'patuakhali', name: 'Patuakhali', nameBn: 'পটুয়াখালী', terminal: 'Patuakhali Terminal', subLocations: [{ id: 'pat-central', name: 'Patuakhali Terminal', nameBn: 'পটুয়াখালী টার্মিনাল' }] },
  { id: 'pirojpur', name: 'Pirojpur', nameBn: 'পিরোজপুর', terminal: 'Pirojpur Bus Stand', subLocations: [{ id: 'pir-central', name: 'Pirojpur Bus Stand', nameBn: 'পিরোজপুর বাস স্ট্যান্ড' }] },
  { id: 'bagerhat', name: 'Bagerhat', nameBn: 'বাগেরহাট', terminal: 'Bagerhat Bus Stand', subLocations: [{ id: 'bag-central', name: 'Bagerhat Bus Stand', nameBn: 'বাগেরহাট বাস স্ট্যান্ড' }] },
  { id: 'chuadanga', name: 'Chuadanga', nameBn: 'চুয়াডাঙ্গা', terminal: 'Chuadanga Terminal', subLocations: [{ id: 'chu-central', name: 'Chuadanga Terminal', nameBn: 'চুয়াডাঙ্গা টার্মিনাল' }] },
  { id: 'jhenaidah', name: 'Jhenaidah', nameBn: 'ঝিনাইদহ', terminal: 'Jhenaidah Terminal', subLocations: [{ id: 'jhe-central', name: 'Jhenaidah Terminal', nameBn: 'ঝিনাইদহ টার্মিনাল' }] },
  { id: 'kushtia', name: 'Kushtia', nameBn: 'কুষ্টিয়া', terminal: 'Kushtia Bus Stand', subLocations: [{ id: 'kus-central', name: 'Kushtia Bus Stand', nameBn: 'কুষ্টিয়া বাস স্ট্যান্ড' }] },
  { id: 'magura', name: 'Magura', nameBn: 'মাগুরা', terminal: 'Magura Terminal', subLocations: [{ id: 'mag-central', name: 'Magura Terminal', nameBn: 'মাগুরা টার্মিনাল' }] },
  { id: 'meherpur', name: 'Meherpur', nameBn: 'মেহেরপুর', terminal: 'Meherpur Bus Stand', subLocations: [{ id: 'meh-central', name: 'Meherpur Bus Stand', nameBn: 'মেহেরপুর বাস স্ট্যান্ড' }] },
  { id: 'narail', name: 'Narail', nameBn: 'নড়াইল', terminal: 'Narail Terminal', subLocations: [{ id: 'nrl-central', name: 'Narail Terminal', nameBn: 'নড়াইল টার্মিনাল' }] },
  { id: 'satkhira', name: 'Satkhira', nameBn: 'সাতক্ষীরা', terminal: 'Satkhira Bus Stand', subLocations: [{ id: 'sat-central', name: 'Satkhira Bus Stand', nameBn: 'সাতক্ষীরা বাস স্ট্যান্ড' }] },
  { id: 'chapainawabganj', name: 'Chapainawabganj', nameBn: 'চাঁপাইনবাবগঞ্জ', terminal: 'Chapainawabganj Terminal', subLocations: [{ id: 'chp-central', name: 'Chapainawabganj Terminal', nameBn: 'চাঁপাইনবাবগঞ্জ টার্মিনাল' }] },
  { id: 'joypurhat', name: 'Joypurhat', nameBn: 'জয়পুরহাট', terminal: 'Joypurhat Bus Stand', subLocations: [{ id: 'joy-central', name: 'Joypurhat Bus Stand', nameBn: 'জয়পুরহাট বাস স্ট্যান্ড' }] },
  { id: 'naogaon', name: 'Naogaon', nameBn: 'নওগাঁ', terminal: 'Naogaon Terminal', subLocations: [{ id: 'nao-central', name: 'Naogaon Terminal', nameBn: 'নওগাঁ টার্মিনাল' }] },
  { id: 'natore', name: 'Natore', nameBn: 'নাটোর', terminal: 'Natore Bus Stand', subLocations: [{ id: 'nat-central', name: 'Natore Bus Stand', nameBn: 'নাটোর বাস স্ট্যান্ড' }] },
  { id: 'pabna', name: 'Pabna', nameBn: 'পাবনা', terminal: 'Pabna Bus Station', subLocations: [{ id: 'pab-central', name: 'Pabna Bus Station', nameBn: 'পাবনা বাস স্টেশন' }] },
  { id: 'gaibandha', name: 'Gaibandha', nameBn: 'গাইবান্ধা', terminal: 'Gaibandha Terminal', subLocations: [{ id: 'gai-central', name: 'Gaibandha Terminal', nameBn: 'গাইবান্ধা টার্মিনাল' }] },
  { id: 'kurigram', name: 'Kurigram', nameBn: 'কুড়িগ্রাম', terminal: 'Kurigram Bus Stand', subLocations: [{ id: 'kur-central', name: 'Kurigram Bus Stand', nameBn: 'কুড়িগ্রাম বাস স্ট্যান্ড' }] },
  { id: 'nilphamari', name: 'Nilphamari', nameBn: 'নীলফামারী', terminal: 'Nilphamari Bus Stand', subLocations: [{ id: 'nil-central', name: 'Nilphamari Bus Stand', nameBn: 'নীলফামারী বাস স্ট্যান্ড' }] },
  { id: 'panchagarh', name: 'Panchagarh', nameBn: 'পঞ্চগড়', terminal: 'Panchagarh Terminal', subLocations: [{ id: 'pan-central', name: 'Panchagarh Terminal', nameBn: 'পঞ্চগড় টার্মিনাল' }] },
  { id: 'thakurgaon', name: 'Thakurgaon', nameBn: 'ঠাকুরগাঁও', terminal: 'Thakurgaon Bus Stand', subLocations: [{ id: 'tha-central', name: 'Thakurgaon Bus Stand', nameBn: 'ঠাকুরগাঁও বাস স্ট্যান্ড' }] },
];

export const PAYMENT_METHODS = [
  {
    id: 'bkash',
    name: 'bKash',
    nameBn: 'বিকাশ',
    logo: '💳',
    color: '#E2136E',
    type: 'mobile-banking',
    instructions: 'Enter your bKash number to proceed',
  },
  {
    id: 'nagad',
    name: 'Nagad',
    nameBn: 'নগদ',
    logo: '💰',
    color: '#F7941D',
    type: 'mobile-banking',
    instructions: 'Enter your Nagad number to proceed',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    nameBn: 'রকেট',
    logo: '🚀',
    color: '#8B1A8B',
    type: 'mobile-banking',
    instructions: 'Enter your Rocket (DBBL) number',
  },
  {
    id: 'upay',
    name: 'Upay',
    nameBn: 'উপায়',
    logo: '💸',
    color: '#0067B3',
    type: 'mobile-banking',
    instructions: 'Enter your Upay wallet number',
  },
  {
    id: 'sslcommerz',
    name: 'Card / Net Banking',
    nameBn: 'কার্ড / নেট ব্যাংকিং',
    logo: '🏦',
    color: '#2563EB',
    type: 'card',
    instructions: 'Pay securely with Visa, Mastercard or Net Banking via SSLCommerz',
  },
  {
    id: 'tap',
    name: 'TAP',
    nameBn: 'ট্যাপ',
    logo: '📲',
    color: '#059669',
    type: 'mobile-banking',
    instructions: 'Enter your TAP wallet number',
  },
];

// Generate seat map (example 40 seats)
export const generateSeatMap = (totalSeats = 40) => {
  const seats = [];
  const bookedSeats = [];
  // Randomly mark ~30% as booked
  for (let i = 1; i <= totalSeats; i++) {
    if (Math.random() < 0.3) bookedSeats.push(i);
  }
  for (let i = 1; i <= totalSeats; i++) {
    seats.push({
      id: i,
      number: i,
      status: bookedSeats.includes(i) ? 'booked' : 'available',
      type: i <= 4 ? 'front' : 'regular',
    });
  }
  return seats;
};
