// TicketKati - Bangladesh Bus & Place Data

export const BUSES = [
  {
    id: 'bus-01',
    name: 'Drutogami Express',
    nameBn: 'দ্রুতগামী এক্সপ্রেস',
    type: 'AC',
    logo: '🚌',
    color: '#E8242A',
    rating: 4.5,
    totalSeats: 40,
    perSeatPrice: 350,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Recliner Seat'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'bogura', 'rangpur'],
    schedule: ['06:00', '08:00', '10:00', '14:00', '18:00', '22:00'],
    description: 'Premium AC service with modern amenities',
  },
  {
    id: 'bus-02',
    name: 'Rajib Paribahan',
    nameBn: 'রাজিব পরিবহন',
    type: 'Non-AC',
    logo: '🚌',
    color: '#1A8A4A',
    rating: 4.2,
    totalSeats: 44,
    perSeatPrice: 200,
    amenities: ['Fan', 'Comfortable Seat', 'Luggage Space'],
    routes: ['dhaka', 'narayanganj', 'cumilla', 'chittagong'],
    schedule: ['07:00', '09:30', '12:00', '15:00', '20:00'],
    description: 'Reliable and affordable inter-city service',
  },
  {
    id: 'bus-03',
    name: 'Hanif Enterprise',
    nameBn: 'হানিফ এন্টারপ্রাইজ',
    type: 'AC',
    logo: '🚌',
    color: '#F5A623',
    rating: 4.7,
    totalSeats: 40,
    perSeatPrice: 500,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Blanket', 'Snacks'],
    routes: ['dhaka', 'sylhet', 'moulvibazar'],
    schedule: ['07:30', '10:00', '13:00', '17:00', '22:30'],
    description: 'Bangladesh\'s most trusted long-route bus service',
  },
  {
    id: 'bus-04',
    name: 'Dhaka-Tangail Bhuyapuri',
    nameBn: 'ঢাকা-টাঙ্গাইল ভূয়াপুরী',
    type: 'Non-AC',
    logo: '🚌',
    color: '#3B82F6',
    rating: 3.9,
    totalSeats: 44,
    perSeatPrice: 150,
    amenities: ['Fan', 'Economy Seat'],
    routes: ['dhaka', 'gazipur', 'tangail', 'mymensingh'],
    schedule: ['06:30', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00'],
    description: 'Frequent daily service on Dhaka-Tangail route',
  },
  {
    id: 'bus-05',
    name: 'Sirajganj Travel',
    nameBn: 'সিরাজগঞ্জ ট্রাভেল',
    type: 'AC',
    logo: '🚌',
    color: '#8B5CF6',
    rating: 4.3,
    totalSeats: 40,
    perSeatPrice: 320,
    amenities: ['AC', 'Recliner Seat', 'USB Charging', 'Water Bottle'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'pabna'],
    schedule: ['06:00', '09:00', '12:00', '15:00', '19:00', '22:00'],
    description: 'Comfortable North Bengal connectivity',
  },
  {
    id: 'bus-06',
    name: 'Lalmonirhat Express',
    nameBn: 'লালমনিরহাট এক্সপ্রেস',
    type: 'AC',
    logo: '🚌',
    color: '#EC4899',
    rating: 4.1,
    totalSeats: 40,
    perSeatPrice: 600,
    amenities: ['AC', 'Blanket', 'Pillow', 'USB Charging', 'Recliner'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'bogura', 'rangpur', 'lalmonirhat'],
    schedule: ['08:00', '14:00', '21:00'],
    description: 'Overnight comfort service to far north',
  },
  {
    id: 'bus-07',
    name: 'Comilla Travel',
    nameBn: 'কুমিল্লা ট্রাভেল',
    type: 'Non-AC',
    logo: '🚌',
    color: '#14B8A6',
    rating: 4.0,
    totalSeats: 44,
    perSeatPrice: 180,
    amenities: ['Fan', 'Comfortable Seat', 'Luggage'],
    routes: ['dhaka', 'narayanganj', 'cumilla', 'feni'],
    schedule: ['06:00', '07:30', '09:00', '11:00', '13:00', '15:00', '17:00', '19:00'],
    description: 'Quick and frequent Dhaka-Comilla runs',
  },
  {
    id: 'bus-08',
    name: "Cox's Bazar Sleeper Coach",
    nameBn: 'কক্সবাজার স্লিপার কোচ',
    type: 'Sleeper',
    logo: '🚌',
    color: '#F97316',
    rating: 4.8,
    totalSeats: 28,
    perSeatPrice: 900,
    amenities: ['AC', 'Sleeper Berth', 'Curtain', 'USB Charging', 'Blanket', 'Pillow', 'Snacks'],
    routes: ['dhaka', 'chittagong', 'coxsbazar'],
    schedule: ['21:00', '22:00', '23:00'],
    description: 'Luxury sleeper berths for overnight travel',
  },
];

export const PLACES = [
  { id: 'dhaka', name: 'Dhaka', nameBn: 'ঢাকা', terminal: 'Sayedabad / Gabtoli / Mohakhali' },
  { id: 'faridpur', name: 'Faridpur', nameBn: 'ফরিদপুর', terminal: 'Faridpur Bus Terminal' },
  { id: 'gazipur', name: 'Gazipur', nameBn: 'গাজীপুর', terminal: 'Chandra Terminal' },
  { id: 'gopalganj', name: 'Gopalganj', nameBn: 'গোপালগঞ্জ', terminal: 'Gopalganj Bus Stand' },
  { id: 'kishoreganj', name: 'Kishoreganj', nameBn: 'কিশোরগঞ্জ', terminal: 'Kishoreganj Terminal' },
  { id: 'madaripur', name: 'Madaripur', nameBn: 'মাদারীপুর', terminal: 'Madaripur Bus Stand' },
  { id: 'manikganj', name: 'Manikganj', nameBn: 'মানিকগঞ্জ', terminal: 'Manikganj Terminal' },
  { id: 'munshiganj', name: 'Munshiganj', nameBn: 'মুন্সীগঞ্জ', terminal: 'Munshiganj Bus Stand' },
  { id: 'narayanganj', name: 'Narayanganj', nameBn: 'নারায়ণগঞ্জ', terminal: 'Narayanganj Bus Stand' },
  { id: 'narsingdi', name: 'Narsingdi', nameBn: 'নরসিংদী', terminal: 'Narsingdi Terminal' },
  { id: 'rajbari', name: 'Rajbari', nameBn: 'রাজবাড়ী', terminal: 'Rajbari Bus Stand' },
  { id: 'shariatpur', name: 'Shariatpur', nameBn: 'শরীয়তপুর', terminal: 'Shariatpur Terminal' },
  { id: 'tangail', name: 'Tangail', nameBn: 'টাঙ্গাইল', terminal: 'Tangail Central Terminal' },
  { id: 'mymensingh', name: 'Mymensingh', nameBn: 'ময়মনসিংহ', terminal: 'Mymensingh Bus Terminal' },
  { id: 'jamalpur', name: 'Jamalpur', nameBn: 'জামালপুর', terminal: 'Jamalpur Bus Stand' },
  { id: 'netrokona', name: 'Netrokona', nameBn: 'নেত্রকোণা', terminal: 'Netrokona Terminal' },
  { id: 'sherpur', name: 'Sherpur', nameBn: 'শেরপুর', terminal: 'Sherpur Bus Stand' },
  { id: 'chittagong', name: 'Chittagong', nameBn: 'চট্টগ্রাম', terminal: 'Dampara Terminal' },
  { id: 'bandarban', name: 'Bandarban', nameBn: 'বান্দরবান', terminal: 'Bandarban Bus Stand' },
  { id: 'brahmanbaria', name: 'Brahmanbaria', nameBn: 'ব্রাহ্মণবাড়িয়া', terminal: 'Brahmanbaria Terminal' },
  { id: 'chandpur', name: 'Chandpur', nameBn: 'চাঁদপুর', terminal: 'Chandpur Bus Stand' },
  { id: 'cumilla', name: 'Cumilla', nameBn: 'কুমিল্লা', terminal: 'Cumilla Bus Stand' },
  { id: 'coxsbazar', name: "Cox's Bazar", nameBn: 'কক্সবাজার', terminal: "Cox's Bazar Terminal" },
  { id: 'feni', name: 'Feni', nameBn: 'ফেনী', terminal: 'Feni Terminal' },
  { id: 'khagrachhari', name: 'Khagrachhari', nameBn: 'খাগড়াছড়ি', terminal: 'Khagrachhari Bus Stand' },
  { id: 'lakshmipur', name: 'Lakshmipur', nameBn: 'লক্ষ্মীপুর', terminal: 'Lakshmipur Terminal' },
  { id: 'noakhali', name: 'Noakhali', nameBn: 'নোয়াখালী', terminal: 'Noakhali Bus Stand' },
  { id: 'rangamati', name: 'Rangamati', nameBn: 'রাঙামাটি', terminal: 'Rangamati Terminal' },
  { id: 'sylhet', name: 'Sylhet', nameBn: 'সিলেট', terminal: 'Kadamtoli Terminal' },
  { id: 'habiganj', name: 'Habiganj', nameBn: 'হবিগঞ্জ', terminal: 'Habiganj Bus Stand' },
  { id: 'moulvibazar', name: 'Moulvibazar', nameBn: 'মৌলভীবাজার', terminal: 'Moulvibazar Terminal' },
  { id: 'sunamganj', name: 'Sunamganj', nameBn: 'সুনামগঞ্জ', terminal: 'Sunamganj Terminal' },
  { id: 'barisal', name: 'Barisal', nameBn: 'বরিশাল', terminal: 'Notullabad Terminal' },
  { id: 'barguna', name: 'Barguna', nameBn: 'বরগুনা', terminal: 'Barguna Bus Stand' },
  { id: 'bhola', name: 'Bhola', nameBn: 'ভোলা', terminal: 'Bhola Terminal' },
  { id: 'jhalokati', name: 'Jhalokati', nameBn: 'ঝালকাঠি', terminal: 'Jhalokati Bus Stand' },
  { id: 'patuakhali', name: 'Patuakhali', nameBn: 'পটুয়াখালী', terminal: 'Patuakhali Terminal' },
  { id: 'pirojpur', name: 'Pirojpur', nameBn: 'পিরোজপুর', terminal: 'Pirojpur Bus Stand' },
  { id: 'khulna', name: 'Khulna', nameBn: 'খুলনা', terminal: 'Sonadanga Terminal' },
  { id: 'bagerhat', name: 'Bagerhat', nameBn: 'বাগেরহাট', terminal: 'Bagerhat Bus Stand' },
  { id: 'chuadanga', name: 'Chuadanga', nameBn: 'চুয়াডাঙ্গা', terminal: 'Chuadanga Terminal' },
  { id: 'jessore', name: 'Jessore', nameBn: 'যশোর', terminal: 'Jessore Bus Stand' },
  { id: 'jhenaidah', name: 'Jhenaidah', nameBn: 'ঝিনাইদহ', terminal: 'Jhenaidah Terminal' },
  { id: 'kushtia', name: 'Kushtia', nameBn: 'কুষ্টিয়া', terminal: 'Kushtia Bus Stand' },
  { id: 'magura', name: 'Magura', nameBn: 'মাগুরা', terminal: 'Magura Terminal' },
  { id: 'meherpur', name: 'Meherpur', nameBn: 'মেহেরপুর', terminal: 'Meherpur Bus Stand' },
  { id: 'narail', name: 'Narail', nameBn: 'নড়াইল', terminal: 'Narail Terminal' },
  { id: 'satkhira', name: 'Satkhira', nameBn: 'সাতক্ষীরা', terminal: 'Satkhira Bus Stand' },
  { id: 'rajshahi', name: 'Rajshahi', nameBn: 'রাজশাহী', terminal: 'Rajshahi Terminal' },
  { id: 'bogura', name: 'Bogura', nameBn: 'বগুড়া', terminal: 'Bogura Bus Station' },
  { id: 'chapainawabganj', name: 'Chapainawabganj', nameBn: 'চাঁপাইনবাবগঞ্জ', terminal: 'Chapainawabganj Terminal' },
  { id: 'joypurhat', name: 'Joypurhat', nameBn: 'জয়পুরহাট', terminal: 'Joypurhat Bus Stand' },
  { id: 'naogaon', name: 'Naogaon', nameBn: 'নওগাঁ', terminal: 'Naogaon Terminal' },
  { id: 'natore', name: 'Natore', nameBn: 'নাটোর', terminal: 'Natore Bus Stand' },
  { id: 'pabna', name: 'Pabna', nameBn: 'পাবনা', terminal: 'Pabna Bus Station' },
  { id: 'sirajganj', name: 'Sirajganj', nameBn: 'সিরাজগঞ্জ', terminal: 'Sirajganj Terminal' },
  { id: 'rangpur', name: 'Rangpur', nameBn: 'রংপুর', terminal: 'Rangpur Central' },
  { id: 'dinajpur', name: 'Dinajpur', nameBn: 'দিনাজপুর', terminal: 'Dinajpur Bus Stand' },
  { id: 'gaibandha', name: 'Gaibandha', nameBn: 'গাইবান্ধা', terminal: 'Gaibandha Terminal' },
  { id: 'kurigram', name: 'Kurigram', nameBn: 'কুড়িগ্রাম', terminal: 'Kurigram Bus Stand' },
  { id: 'lalmonirhat', name: 'Lalmonirhat', nameBn: 'লালমনিরহাট', terminal: 'Lalmonirhat Terminal' },
  { id: 'nilphamari', name: 'Nilphamari', nameBn: 'নীলফামারী', terminal: 'Nilphamari Bus Stand' },
  { id: 'panchagarh', name: 'Panchagarh', nameBn: 'পঞ্চগড়', terminal: 'Panchagarh Terminal' },
  { id: 'thakurgaon', name: 'Thakurgaon', nameBn: 'ঠাকুরগাঁও', terminal: 'Thakurgaon Bus Stand' },
];

export const PAYMENT_METHODS = [
  {
    id: 'bkash',
    name: 'bKash',
    nameBn: 'বিকাশ',
    logo: '💳',
    color: '#E2136E',
    type: 'mobile-banking',
    instructions: 'Enter your bKash number to proceed',
  },
  {
    id: 'nagad',
    name: 'Nagad',
    nameBn: 'নগদ',
    logo: '💰',
    color: '#F7941D',
    type: 'mobile-banking',
    instructions: 'Enter your Nagad number to proceed',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    nameBn: 'রকেট',
    logo: '🚀',
    color: '#8B1A8B',
    type: 'mobile-banking',
    instructions: 'Enter your Rocket (DBBL) number',
  },
  {
    id: 'upay',
    name: 'Upay',
    nameBn: 'উপায়',
    logo: '💸',
    color: '#0067B3',
    type: 'mobile-banking',
    instructions: 'Enter your Upay wallet number',
  },
  {
    id: 'sslcommerz',
    name: 'Card / Net Banking',
    nameBn: 'কার্ড / নেট ব্যাংকিং',
    logo: '🏦',
    color: '#2563EB',
    type: 'card',
    instructions: 'Pay securely with Visa, Mastercard or Net Banking via SSLCommerz',
  },
  {
    id: 'tap',
    name: 'TAP',
    nameBn: 'ট্যাপ',
    logo: '📲',
    color: '#059669',
    type: 'mobile-banking',
    instructions: 'Enter your TAP wallet number',
  },
];

// Generate seat map (example 40 seats)
export const generateSeatMap = (totalSeats = 40) => {
  const seats = [];
  const bookedSeats = [];
  // Randomly mark ~30% as booked
  for (let i = 1; i <= totalSeats; i++) {
    if (Math.random() < 0.3) bookedSeats.push(i);
  }
  for (let i = 1; i <= totalSeats; i++) {
    seats.push({
      id: i,
      number: i,
      status: bookedSeats.includes(i) ? 'booked' : 'available',
      type: i <= 4 ? 'front' : 'regular',
    });
  }
  return seats;
};
