// TicketKati - Bangladesh Bus & Place Data

export const BUSES = [
  {
    id: 'bus-01',
    name: 'Drutogami Express',
    nameBn: 'দ্রুতগামী এক্সপ্রেস',
    type: 'AC',
    logo: '🚌',
    color: '#E8242A',
    rating: 4.5,
    totalSeats: 40,
    perSeatPrice: 350,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Recliner Seat'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'bogura', 'rangpur'],
    schedule: ['06:00', '08:00', '10:00', '14:00', '18:00', '22:00'],
    description: 'Premium AC service with modern amenities',
  },
  {
    id: 'bus-02',
    name: 'Rajib Paribahan',
    nameBn: 'রাজিব পরিবহন',
    type: 'Non-AC',
    logo: '🚌',
    color: '#1A8A4A',
    rating: 4.2,
    totalSeats: 44,
    perSeatPrice: 200,
    amenities: ['Fan', 'Comfortable Seat', 'Luggage Space'],
    routes: ['dhaka', 'narayanganj', 'cumilla', 'chittagong'],
    schedule: ['07:00', '09:30', '12:00', '15:00', '20:00'],
    description: 'Reliable and affordable inter-city service',
  },
  {
    id: 'bus-03',
    name: 'Hanif Enterprise',
    nameBn: 'হানিফ এন্টারপ্রাইজ',
    type: 'AC',
    logo: '🚌',
    color: '#F5A623',
    rating: 4.7,
    totalSeats: 40,
    perSeatPrice: 500,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Blanket', 'Snacks'],
    routes: ['dhaka', 'sylhet', 'moulvibazar'],
    schedule: ['07:30', '10:00', '13:00', '17:00', '22:30'],
    description: 'Bangladesh\'s most trusted long-route bus service',
  },
  {
    id: 'bus-04',
    name: 'Dhaka-Tangail Bhuyapuri',
    nameBn: 'ঢাকা-টাঙ্গাইল ভূয়াপুরী',
    type: 'Non-AC',
    logo: '🚌',
    color: '#3B82F6',
    rating: 3.9,
    totalSeats: 44,
    perSeatPrice: 150,
    amenities: ['Fan', 'Economy Seat'],
    routes: ['dhaka', 'gazipur', 'tangail', 'mymensingh'],
    schedule: ['06:30', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00'],
    description: 'Frequent daily service on Dhaka-Tangail route',
  },
  {
    id: 'bus-05',
    name: 'Sirajganj Travel',
    nameBn: 'সিরাজগঞ্জ ট্রাভেল',
    type: 'AC',
    logo: '🚌',
    color: '#8B5CF6',
    rating: 4.3,
    totalSeats: 40,
    perSeatPrice: 320,
    amenities: ['AC', 'Recliner Seat', 'USB Charging', 'Water Bottle'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'pabna'],
    schedule: ['06:00', '09:00', '12:00', '15:00', '19:00', '22:00'],
    description: 'Comfortable North Bengal connectivity',
  },
  {
    id: 'bus-06',
    name: 'Lalmonirhat Express',
    nameBn: 'লালমনিরহাট এক্সপ্রেস',
    type: 'AC',
    logo: '🚌',
    color: '#EC4899',
    rating: 4.1,
    totalSeats: 40,
    perSeatPrice: 600,
    amenities: ['AC', 'Blanket', 'Pillow', 'USB Charging', 'Recliner'],
    routes: ['dhaka', 'gazipur', 'tangail', 'sirajganj', 'bogura', 'rangpur', 'lalmonirhat'],
    schedule: ['08:00', '14:00', '21:00'],
    description: 'Overnight comfort service to far north',
  },
  {
    id: 'bus-07',
    name: 'Comilla Travel',
    nameBn: 'কুমিল্লা ট্রাভেল',
    type: 'Non-AC',
    logo: '🚌',
    color: '#14B8A6',
    rating: 4.0,
    totalSeats: 44,
    perSeatPrice: 180,
    amenities: ['Fan', 'Comfortable Seat', 'Luggage'],
    routes: ['dhaka', 'narayanganj', 'cumilla', 'feni'],
    schedule: ['06:00', '07:30', '09:00', '11:00', '13:00', '15:00', '17:00', '19:00'],
    description: 'Quick and frequent Dhaka-Comilla runs',
  },
  {
    id: 'bus-08',
    name: "Cox's Bazar Sleeper Coach",
    nameBn: 'কক্সবাজার স্লিপার কোচ',
    type: 'Sleeper',
    logo: '🚌',
    color: '#F97316',
    rating: 4.8,
    totalSeats: 28,
    perSeatPrice: 900,
    amenities: ['AC', 'Sleeper Berth', 'Curtain', 'USB Charging', 'Blanket', 'Pillow', 'Snacks'],
    routes: ['dhaka', 'chittagong', 'coxsbazar'],
    schedule: ['21:00', '22:00', '23:00'],
    description: 'Luxury sleeper berths for overnight travel',
  },
];

export const PLACES = [
  { id: 'dhaka', name: "Dhaka", nameBn: 'ঢাকা', terminal: 'Sayedabad / Gabtoli' },
  { id: 'gazipur', name: 'Gazipur', nameBn: 'গাজীপুর', terminal: 'Chandra Terminal' },
  { id: 'narayanganj', name: 'Narayanganj', nameBn: 'নারায়ণগঞ্জ', terminal: 'Narayanganj Bus Stand' },
  { id: 'tangail', name: 'Tangail', nameBn: 'টাঙ্গাইল', terminal: 'Tangail Central Terminal' },
  { id: 'mymensingh', name: 'Mymensingh', nameBn: 'ময়মনসিংহ', terminal: 'Mymensingh Bus Terminal' },
  { id: 'sirajganj', name: 'Sirajganj', nameBn: 'সিরাজগঞ্জ', terminal: 'Sirajganj Terminal' },
  { id: 'bogura', name: 'Bogura', nameBn: 'বগুড়া', terminal: 'Bogura Bus Station' },
  { id: 'rangpur', name: 'Rangpur', nameBn: 'রংপুর', terminal: 'Rangpur Central' },
  { id: 'lalmonirhat', name: 'Lalmonirhat', nameBn: 'লালমনিরহাট', terminal: 'Lalmonirhat Terminal' },
  { id: 'pabna', name: 'Pabna', nameBn: 'পাবনা', terminal: 'Pabna Bus Station' },
  { id: 'rajshahi', name: 'Rajshahi', nameBn: 'রাজশাহী', terminal: 'Rajshahi Terminal' },
  { id: 'khulna', name: 'Khulna', nameBn: 'খুলনা', terminal: 'Sonadanga Terminal' },
  { id: 'jessore', name: 'Jessore', nameBn: 'যশোর', terminal: 'Jessore Bus Stand' },
  { id: 'sylhet', name: 'Sylhet', nameBn: 'সিলেট', terminal: 'Kadamtoli Terminal' },
  { id: 'moulvibazar', name: 'Moulvibazar', nameBn: 'মৌলভীবাজার', terminal: 'Moulvibazar Terminal' },
  { id: 'cumilla', name: 'Cumilla', nameBn: 'কুমিল্লা', terminal: 'Cumilla Bus Stand' },
  { id: 'feni', name: 'Feni', nameBn: 'ফেনী', terminal: 'Feni Terminal' },
  { id: 'chittagong', name: 'Chittagong', nameBn: 'চট্টগ্রাম', terminal: 'Dampara Terminal' },
  { id: 'coxsbazar', name: "Cox's Bazar", nameBn: "কক্সবাজার", terminal: "Cox's Bazar Terminal" },
  { id: 'barisal', name: 'Barisal', nameBn: 'বরিশাল', terminal: 'Notullabad Terminal' },
];

export const PAYMENT_METHODS = [
  {
    id: 'bkash',
    name: 'bKash',
    nameBn: 'বিকাশ',
    logo: '💳',
    color: '#E2136E',
    type: 'mobile-banking',
    instructions: 'Enter your bKash number to proceed',
  },
  {
    id: 'nagad',
    name: 'Nagad',
    nameBn: 'নগদ',
    logo: '💰',
    color: '#F7941D',
    type: 'mobile-banking',
    instructions: 'Enter your Nagad number to proceed',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    nameBn: 'রকেট',
    logo: '🚀',
    color: '#8B1A8B',
    type: 'mobile-banking',
    instructions: 'Enter your Rocket (DBBL) number',
  },
  {
    id: 'upay',
    name: 'Upay',
    nameBn: 'উপায়',
    logo: '💸',
    color: '#0067B3',
    type: 'mobile-banking',
    instructions: 'Enter your Upay wallet number',
  },
  {
    id: 'sslcommerz',
    name: 'Card / Net Banking',
    nameBn: 'কার্ড / নেট ব্যাংকিং',
    logo: '🏦',
    color: '#2563EB',
    type: 'card',
    instructions: 'Pay securely with Visa, Mastercard or Net Banking via SSLCommerz',
  },
  {
    id: 'tap',
    name: 'TAP',
    nameBn: 'ট্যাপ',
    logo: '📲',
    color: '#059669',
    type: 'mobile-banking',
    instructions: 'Enter your TAP wallet number',
  },
];

// Generate seat map (example 40 seats)
export const generateSeatMap = (totalSeats = 40) => {
  const seats = [];
  const bookedSeats = [];
  // Randomly mark ~30% as booked
  for (let i = 1; i <= totalSeats; i++) {
    if (Math.random() < 0.3) bookedSeats.push(i);
  }
  for (let i = 1; i <= totalSeats; i++) {
    seats.push({
      id: i,
      number: i,
      status: bookedSeats.includes(i) ? 'booked' : 'available',
      type: i <= 4 ? 'front' : 'regular',
    });
  }
  return seats;
};
